### ISSUE TITLE
Uranium 235/238 Fill Output Belt numbers are off

### ISSUE THREAD

**Issue by s3bash** [DDDGamer/factorio-cheat-sheet#12]
The numbers for u235/u238 to fill yellow/red/blue belts are off. 

They should be yellow: 178, Red: 356, Blue: 534

Buildings = Belt throughput / ( crafting speed * (items produced/crafting time) )
Blue = 40 / (0.75 * (1/10))
Red = 40 (2/3) / (0.75 * (1/10))
Yellow = (40/3) / (0.75 * (1/10))

**Comment by DDDGamer** [comment]
Thanks, you are right, i think i multiplied the input(which was rounded) by 10, should have done the calculation instead to be more accurate.
