### ISSUE TITLE
Recommend explicit Single Reactor Equivalent unit for nuclear power section.

### ISSUE THREAD

**Issue by hovissimo** [DDDGamer/factorio-cheat-sheet#36]
This is already addressed the nuke section, but not very clearly.  I recommend adopting the Single Reactor Equivalent (SRE) unit to describe potential power generation in reactor setups (Where a single reactor produces one SRE worth of power and three reactors in a line produce 2 + 3 + 2 = 7 SRE worth of power.)

Spending a paragraph describing the unit and the adjacency bonus would allow the remainder of the documentation to be simplified and abridged by making everything based on the now-understood SRE unit.

**Comment by hovissimo** [comment]
As a side note, you mention that 2xN reactor setups are the most efficient while retaining access - it might also be worth mentioning that deeper MxN setups are not only inconvenient but only barely more efficient anyway.

16 reactors, 2x8, is `4*3 + 12*4 = 60` SRE
16 reactors, 4x4, is `4*3 + 8*4 + 4*5 = 64` SRE

Making an SRE diagram is a really easy way to understand this, too:

```
3 4 4 4 4 4 4 3
3 4 4 4 4 4 4 3

3 4 4 3
4 5 5 4
4 5 5 4
3 4 4 3
```

**Comment by DDDGamer** [comment]
Had to think about this for a bit, but i got the info in, thanks

**Comment by hovissimo** [comment]
Looks great.

It might be worth using the Single Reactor Equivalent unit here and here:
![image](https://user-images.githubusercontent.com/6434414/33460173-cd472958-d5e1-11e7-876b-293db4ec6a6b.png)


Side note:  I recently [did the math](https://www.reddit.com/r/factorio/comments/7f4tbh/165mw_tileable_solar_radar_robo_9999_perfect_ratio/dqb1bn1/) on heat waste and decided that trying to get every joule out of a fuel cell is a complete waste of time and UPS.  This might be worth mentioning on the cheat sheet. (Please check my math, of course).

Other side note: The link to the cheat sheet in the readme appears broken.

**Comment by hovissimo** [comment]
Reviewing my own math, I had an error in that I neglected the ore -> U-238 refinement step.  It's still really easy to keep your reactors fed constantly, regardless of load.
