### ISSUE TITLE
Prod modules in research don't lose progress

### ISSUE THREAD

**Issue by tzwaan** [DDDGamer/factorio-cheat-sheet#41]
There's a note with a link to a video by xterminator in the part about prod modules in labs.

This information is actually wrong. Yes, the bars reset when you switch research, but you don't actually lose any progress, since the progress from both the regular and the productivity bar are continiously added to the total when doing research.

For example:

- Build 10 labs.
- Give each lab 1 red pack
- Research automation.

The packs will all be exactly gone when research completes.

Now do the same, but with prod modules and you'll see that all labs will have an equal amount of packs left after finishing the research, and none of the labs will have actually finished a full cycle.

**Comment by DDDGamer** [comment]
Hey, sorry i forgot to reply, ill be doing a bulk update for 0.16 and include this in there after verification that is still the case in 0.16
Thanks for the report!

**Comment by Sachbir** [comment]
Tested in 0.16.7

The productivity bar **does** reset when a research completes, just as demonstrated in the Xterminator video. 
tzwaan seems to be saying that the _Science Packs_ are not wasted on completion, which is true, but not what the Cheat Sheet describes.

**Comment by DDDGamer** [comment]
Huh, that's interesting, i would assume that if bar resets that implies that you would not get the productivity bonus, but in reality you do? This might be a visual bug worth reporting and getting more info in from the Factorio devs?

**Comment by tzwaan** [comment]
Exactly. The bar resets, but at that point the productivity has already been added to the total research progress, so nothing is lost. So the warning about not putting prods into the labs in the early to mid game is totally unwarrented.

You could report it as a bug, but I don't think the devs will consider this one, since I believe it's working as intended. Science isn't cycle based (where it will only add on a full cycle), because if that were the case, having 10 labs research automation 1 would result in the bar going from 0 to 100 instantly when the labs all finish their cycle. Instead what happens is that the progress is added to the total every tick. This is the case with the prod bar as well.

And since the recipe changes everytime the research changes, we would actually expect the productivity bar to reset.

**Comment by Sachbir** [comment]
I believe tzwaan is right, and that I was misreading the situation previously. A silly error in retrospect.

I also agree that it's more intended than it is a bug, as the productivity is not granted as a lump sum but incremental. There are possibly better ways to show it (Eg. Depicting the green and purple bars on the same line) but this is a suggestion, not a fix.

**Comment by DDDGamer** [comment]
This false info has been removed
