### ISSUE TITLE
Fluidwagon can't be split in 3 seperate compartments anymore from version 0.16.7

### ISSUE THREAD

**Issue by HonkingGoose** [DDDGamer/factorio-cheat-sheet#42]
The fluidwagon has changed starting from Factorio version 0.16.7, the fluidwagon is now 1 tank, instead of 3 smaller tanks. So the picture and the text relating to the "Separated Wagon Tanks" can be removed, because this functionality is not in the base game anymore.

Link for the changelog for version 0.16.7:
https://www.reddit.com/r/factorio/comments/7lbkiz/version_0167/

See the Factorio Friday for the developers thinking on this:
https://www.factorio.com/blog/post/fff-222

**Comment by DDDGamer** [comment]
Thanks, is the change final though? I think im going to wait a bit, make sure it is.
Thanks for the report!

**Comment by HonkingGoose** [comment]
The developers made the change to make the fluidwagon easier to use, but there has been some feedback in the Reddit Factorio forum, that people don't like the change. So it is too early to tell if the change will  be final or not. So I think it is best to wait a bit, see what happens. :)

By the way, the developers also hinted (in Friday Facts 222) at a change in fluidwagon capacity from 75k to some smaller amount. Most probably 25k (amount in regular land based fluid storage tank). From the developer V453000: https://www.reddit.com/r/factorio/comments/7lkuh2/friday_facts_222_christmas_avalanche/droah2n/
So that's also a thing that might change later.

**Comment by DDDGamer** [comment]
Exactly, until its all finalized ill hold of on the update otherwise ill be just chasing the changes

**Comment by DDDGamer** [comment]
Storage Tanks splitting removed, capacity updated.
