### ISSUE TITLE
Undergrounds and Sideloading doesn't compress in 0.16. 

### ISSUE THREAD

**Issue by ritobanrc** [DDDGamer/factorio-cheat-sheet#45]
The title.

**Comment by justinwzig** [comment]
The cheatsheet isn't updated for 0.16, it only claims to be updated for 0.15. Presumably, a full update will be done once 0.16 is stable.

**Comment by DDDGamer** [comment]
That is correct

**Comment by DDDGamer** [comment]
I don't think I specifically stated these compression hacks, and the latest FFF (https://www.factorio.com/blog/post/fff-231) now has compression by default with inserters.
So this issue is now irrelevant i think, pleas confirm?

**Comment by DDDGamer** [comment]
nvm, found a reference in inserter sheet and removed it.
