### ISSUE TITLE
Spelling Mistake 

### ISSUE THREAD

**Issue by Joe-Games** [DDDGamer/factorio-cheat-sheet#58]
![capture](https://user-images.githubusercontent.com/38812993/39397374-2bd70194-4af6-11e8-9e2a-d756c046932a.PNG)
Should Be 
For **Lazy Bastard Achievement** Open Console, type `/permissions`, Disable _Craft_

**Comment by DDDGamer** [comment]
fixed by @davepeake, thanks y'all!

**Comment by DDDGamer** [comment]
Looks like Achievement is still wrong, fixed now

**Comment by Joe-Games** [comment]
No problem lol
