### ISSUE TITLE
Number error in Nuclear

### ISSUE THREAD

**Issue by TideSinger** [DDDGamer/factorio-cheat-sheet#65]
![Pretty sure it should be 1000, not 10000](https://user-images.githubusercontent.com/24493315/41327574-0913798e-6e92-11e8-9bd9-d5859a5c4a37.png)
Pretty sure it should be 1000, not 10000

**Comment by DDDGamer** [comment]
Nope, thats correct, has been discussed already
see 
https://github.com/DDDGamer/factorio-cheat-sheet/issues/53
https://www.reddit.com/r/factorio/comments/761o4u/the_factorio_cheat_sheet_v015/doc81yj/
