### ISSUE TITLE
1:2 train ratio is wrong

### ISSUE THREAD

**Issue by tzwaan** [DDDGamer/factorio-cheat-sheet#68]
In the train speed section there's a note saying that the ratio of 1 locomotive to 2 wagons is optimal and is the ratio to maintain the maximum speed.

However, this information is more than 2 years old, and no longer accurate.

The current fuel table clearly shows that this is no longer the case, and a newer source for the accurate information is also given in the same section.

The 1:2 statement and the accompanying link to reddit should be removed.

**Comment by DDDGamer** [comment]
Removed
