### ISSUE TITLE
[Feature] Add reactor efficiency in nuclear ratio

### ISSUE THREAD

**Issue by itchylol742** [DDDGamer/factorio-cheat-sheet#72]
Example image (the finished product would have a proper symbol with properly sized and lined up text):
![image](https://user-images.githubusercontent.com/42976312/46585664-7d611700-ca41-11e8-9698-b28e733119ca.png)

I can work on this issue, but would like to get it approved first.

**Comment by DDDGamer** [comment]
Is that the right calculation? Im a bit rusty on the nuclear stuff haven't done it in a while. i.e How are you getting to the percentages?

**Comment by itchylol742** [comment]
Total power generation / power generation if each reactor was working individually

For example, with 4 reactors, it's 480MW/160MW which is 300%. This means with 4 reactors together, the reactors are 300% as efficient compared to if they were working separately.

**Comment by DDDGamer** [comment]
Oh I see, that is something it would be pretty neat to see a graph for actually, theoretically it should start leveling off as you go up in reactor count. But anyway, yeah I'm ok with it if it fits, the table maybe too wide with an extra cell.
